Repository mines-erds/core-ct, pull requests merged in 2023-09, with the labels that each got.

#12 Created Initial README
  README.md
Labels: documentation

#13 Add DICOM importing
  .gitignore
  src/importers.py
  src/test_dicom.py
Labels: feature

#14 Add Core class
  core.py
Labels: feature

#15 Create Analysis class with its brightness trace method
  analysis.py
Labels: feature

#24 Organize Repository and Get Python Dependencies Managed
  .gitignore
  LICENSE
  README.md
  analysis.py
  poetry.lock
  pyproject.toml
  src/core_ct/__init__.py
  src/core_ct/analysis.py
  src/core_ct/core.py
  src/core_ct/importers.py
  tests/__init__.py
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000500.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000501.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000502.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000503.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000504.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000505.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000506.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000507.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000508.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000509.dcm
  tests/scans/PAT_4636_39L_0001/PAT_4636_39L_0001_000510.dcm
  tests/test_dicom.py
  tests/test_import.py
Labels: organization
